version: '3'
services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - ./media:/app/media
      - ./db:/app/db
    environment:
      - BOT_TOKEN=7046888785:AAHA_DVDVz3ry93xMQVDlvImi21zXtotyLw
      - GRAPHHOPPER_TOKEN=41b99b2f-0843-4ccc-947b-89ef6cefade4
      - FORSQUARE_TOKEN=fsq3n82dG/o43vPRF1tApjgx2Z2wqeVjAzmYRO6KFEG7VZc=
      - YANDEX_TILES_TOKEN=3e88d9f7-785e-434f-af61-30864930eae3
      - YANDEX_ORG_TOKEN=dfac9118-8857-4bac-a6f4-099871519e81
      - RUNNING_DOCKER=1



