version: '3'
services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - ./media:/app/media
      - ./db:/app/db
    environment:
      - BOT_TOKEN=7046888785:AAEvFNFDmN2qsunOYzQ0lqx1uAQR7t3F58U



