version: '3'
services:
  redis:
    image: redis:latest
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
      - media_data:/media
  rust_app:
    build:
      context: .
      dockerfile: Dockerfile
    depends_on:
      - redis

volumes:
  redis_data:
  media_data:

