version: '3'
services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - ./media:/app/media
      - ./db:/app/db
    environment:
      - BOT_TOKEN=
      - GRAPHHOPPER_TOKEN=
      - FORSQUARE_TOKEN=
      - YANDEX_TILES_TOKEN=
      - YANDEX_ORG_TOKEN=
      - AMADEUS_TOKEN=
      - AMADEUS_SECRET=
      - AAI_TOKEN=



